// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f0f90710-6c21-4eb0-9d24-17805a016e9c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_fwBGY5LWd",
    "aws_user_pools_web_client_id": "6t1p8b4uve2f1ctccl6dfsf81b",
    "oauth": {},
    "aws_user_files_s3_bucket": "youtest3-test",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
